### ISSUE TITLE
Clicking on notification also triggers full screen grab

### ISSUE THREAD

**Issue by supsm** [TheJoeFin/Text-Grab#109]
When I click on a notification from a full screen grab, it also triggers another full screen grab, as well as the actual window.

![image](https://user-images.githubusercontent.com/60897356/134792666-86227b4a-e6a0-45da-9078-4ab47e2fa188.png)
The slight yellow tint is due to full screen grab being active (the background is completely white), the cursor goes away when I screenshot.

Info:
Text grab version 2.2
Windows 11 insider build 22463

**Comment by TheJoeFin** [comment]
This was a known issue (#98) and has been fixed. Hopefully I will release 2.3 to the Microsoft Store this weekend.

**Comment by supsm** [comment]
Ah, I probably forgot to update my text grab. Thanks!
