### ISSUE TITLE
Request : Right Click menu options to start, copy area via mouse, and stop.

### ISSUE THREAD

**Issue by kaiserc** [TheJoeFin/Text-Grab#12]
First, Great work Great Tool
 
Request : Right Click menu options to start, copy area via mouse, and stop.

This should make it easier and quicker to use. Either that or do something similar to ms snip.

**Comment by TheJoeFin** [comment]
@kaiserc can you go into more detail what you are requesting here. Right now Text Grab enables clicking a word and selecting an area, are you suggesting a new capture method or just a delayed start in how it works today?

**Comment by Martin5001** [comment]
Of course I wouldn't know, but I think he meant a new capture method. If so, I agree with that. It would be nice to have some way to open the app quickly other than just pinning it to taskbar. (Because some might prefer to have something else on the taskbar but still want to have access to TG.)

**Comment by TheJoeFin** [comment]
@Martin5001 that sounds like you are suggesting a global shortcut key? I have also been looking into adding Text Grab to the context menu of image files. #8 

I have considered the idea of having a persistent frame which can be moved around and resized, but which does not go away when text is grabbed. This might be easier to use when doing lots of repetitive tasks where text is generally in the same space. I'll probably open a new issue for this mode.

**Comment by Martin5001** [comment]
Yes, in my opinion, global shortcut key would be the best option. (It would probably require a background-running service, which I understand has its disadvantages, so it might be just an optional setting?) The persistent frame idea sounds useful too.

**Comment by TheJoeFin** [comment]
With the release of Text Grab 2.0, the Grab Frame has been introduced. 

- Does that satisfy this issue?
- What other changes need to be made to satisfy this issue?
