### ISSUE TITLE
Option for background process

### ISSUE THREAD

**Issue by supsm** [TheJoeFin/Text-Grab#122]
Text-Grab takes a while to launch sometimes, so I think it may be better for some users to have a background process. It can be an option that is disabled by default.

**Comment by TheJoeFin** [comment]
It isn't the same as a background process, but I use the Edit Text Window as a persistent window. I set Edit Text as default and toggle the option in the Edit Text Window menu > Window > Open Fullscreen On Launch

Then I get the Fullscreen on launch, and a persistent window which I use to edit and correct the text. Also, if you have an Edit Text Window already open you can add more text to that window. Capture > New Fullscreen Grab (or press ctrl + F).
