### ISSUE TITLE
Upgrade to .NET 6

### ISSUE THREAD

**Issue by TheJoeFin** [TheJoeFin/Text-Grab#124]

**Comment by DocBrown101** [comment]
This should be very easy!

**Comment by TheJoeFin** [comment]
I did a test where I bumped the version in the project, and it worked; super easy! But I would like to look into if there are any new project options to take advantage of with .NET 6

**Comment by AntonOks** [comment]
> I did a test where I bumped the version in the project, and it worked; super easy! But I would like to look into if there are any new project options to take advantage of with .NET 6

I was just to open a "bug request"... and happy I checked the known issues first... and found this one here...

So maybe you first "bumb the version" to ensure text-grab continues to work wherever pkg managers or people did update .NET to v6 already... and then feel free to take some time to "improve and enhance"... ;)
