### ISSUE TITLE
Option to open silently in background automatically at windows startup

### ISSUE THREAD

**Issue by shockproof22** [TheJoeFin/Text-Grab#142]
technically I can set this to start at startup by placing shortcut in startup folder but whenever I log in on the first startup after shutdown or restart it open in text grab full screen and i have to click it away which is annoying.
so it should start silently in background on startup.

**Comment by TheJoeFin** [comment]
Same as #133 I plan on adding this functionality. First attempt will be similar to how it works here: 

https://docs.microsoft.com/en-us/uwp/api/Windows.ApplicationModel.StartupTask?view=winrt-22000

**Comment by shockproof22** [comment]
> Same as #133 I plan on adding this functionality
so how soon can I see this implemented?

**Comment by TheJoeFin** [comment]
Are you looking for the change in code, in the released EXE on the GitHub repo, or in the app from the Microsoft Store?

**Comment by TheJoeFin** [comment]
Initial commit here: https://github.com/TheJoeFin/Text-Grab/commit/317530c1b099361a3dce5a8061bac225e83f7771 

- [ ] Check for Startup Setting
- [ ] Set Startup Setting in Settings Window
- [ ] Investigate if there are new ways to do StartupTask with packaged desktop apps

**Comment by shockproof22** [comment]
> Are you looking for the change in code, in the released EXE on the GitHub repo, or in the app from the Microsoft Store?

looking for changes in the app available on GitHub, haven't used the store app it's paid anyways

**Comment by TheJoeFin** [comment]
Unfortunately with Windows 10 the API used to set startup tasks is not compatible with the single unpackaged EXE distribution. I don't think there is a new API so this feature will be only available through the MSIX packaged app via the Microsoft Store. 

I am still looking into this, but it could be a major roadblock for getting this feature released.

**Comment by shockproof22** [comment]
I understand.
But at least change it so that when I manually set the program to start using "startup" folder, it doesn't immediately go to full screen grab and just start SILENTLY without doing anything.

cause right now it just goes to automatically goes to full screen grab even when I open the app for the first time after shutdown/restart which is really annoying.

simple feature suggestion is -> when opening for first time after shutdown/restart WAIT for my keyboard shortcut to do anything; or show a GUI with all the things that are currently accessed via "settings" menu in taskbar.

I would prefer silent opening in background to a GUI (keyboard shortcuts are more efficient than a GUI interface)

so show this GUI interface on opening and do not go into screen grab by itself,
![S (221) (09-08)](https://user-images.githubusercontent.com/60001922/152627499-d531a4d2-abee-4515-8b7c-c159c2029d1d.png)

this I think is the least you could do to make UX a little better cause honestly that is the only drawback rn of the wonderful and fast app.

**Comment by TheJoeFin** [comment]
@shockproof22 please try pre-release 2.5.0 and see if that works well.

**Comment by shockproof22** [comment]
> @shockproof22 please try pre-release 2.5.0 and see if that works well.

will do!
