### ISSUE TITLE
When used in a multimonitor environment, Text Grab kills taskbar window previews on the monitor it was used on

### ISSUE THREAD

**Issue by jdrch** [TheJoeFin/Text-Grab#15]
How to reproduce:

1. Use Text Grab in a multimonitor environment
2. Mouseover taskbar open application icons on the monitor on which Text Grab was used. You'll notice that preview thumbnails no longer appear for those windows.

**Comment by TheJoeFin** [comment]
Hello @jdrch can you confirm this issue still happens with Text Grab version 1.3?

**Comment by jdrch** [comment]
Fixed, thanks! However, Text Grab is only working on 2 of my 3 monitors. Is there a way for it to dynamically detect and be invoked for all connected monitors at once?
