### ISSUE TITLE
Feature Request: Tray w/o Shortcuts

### ISSUE THREAD

**Issue by djfdat** [TheJoeFin/Text-Grab#155]
Could we get an option to keep Text-Grab running in the background so that it can stay in the System Tray, while not having the hotkeys applied? 

I know that it doesn't make too much of a difference, since I can just avoid using those hotkeys, but I do feel like those settings should be separate.

**Comment by TheJoeFin** [comment]
Could relate to #138, add more control over global shortcut keys.
