### ISSUE TITLE
missing .NET

### ISSUE THREAD

**Issue by hxse** [TheJoeFin/Text-Grab#167]
I have installed .net from this [url](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-6.0.5-windows-x86-installer) but it is still pop up.
![image](https://user-images.githubusercontent.com/22582226/169685143-1dcf782c-c29a-43e5-8b15-49eff6b97a19.png)
windows 10 LTSC 21H2

**Comment by TheJoeFin** [comment]
Try installing this:

**Comment by hxse** [comment]
x64 runtime solved.
