### ISSUE TITLE
Not working anymore - Windows 11 Beta?

### ISSUE THREAD

**Issue by andersberglund** [TheJoeFin/Text-Grab#173]
Text-Grab stopped working and I guess it has something to do with the latest beta release of Windows.
I have tried several versions and the store version, none of them works.
I'm on Windows 11 Beta version 22621.160.

Any suggestions?

**Comment by TheJoeFin** [comment]
Hello, sorry to hear Text Grab stopped working for you, could you be more specific as to how much of Text Grab stopped working?

Does a window pop up? what mode were you trying to use (Fullscreen grab, Grab Frame, Edit Text Window)? What type of computer do you have? 

I did test out Text Grab on the Windows Insider Dev channel and Release Preview with no issue. Looking forward to your response.

**Comment by andersberglund** [comment]
Hello

Thanks for a fast reply.

I have tried both Fullscreen grab and Grab frame. Both shows and I can select a rectangle in full screen, and words in grab frame.
There is a bit longer delay than  when it worked but then the full screen overlay disappears and grab frame also disappears but nothing is copied to clipboard.

**Comment by TheJoeFin** [comment]
If you open the "Event Viewer" and under "Windows Logs" on the left hand pane, click "Application" then the crashes should show up. I am not seeing any crash data in the developer dashboard for the Microsoft Store version. It could be possible there is a conflict with the version of .NET 6, but that shouldn't not affect the Store version of Text Grab. Hopefully the crash in the Event Viewer will give more information and explain why it is crashing.

**Comment by andersberglund** [comment]
There is no crash events in the application log. I tried several "grabs" in a row and sometimes it works and next time I try the same words it doesn't work. I have used it in several applications to get a clear black on white text but that doesn't help.
 It's like 1 read and 5 nothing. It feels like OCR can't read it?

**Comment by TheJoeFin** [comment]
What is your keyboard language set to? What language are you trying to OCR? Can you provide reference images?

**Comment by andersberglund** [comment]
My keyboard language is swedish. I have tried both english and swedish. It doesn't have any problems with swedish characters like ÅÄÖ.

![image](https://user-images.githubusercontent.com/2539487/174496258-d94eb151-d3c6-4dd0-8bc0-7393273900ce.png)

![image](https://user-images.githubusercontent.com/2539487/174496278-1a65dda0-22e0-41cc-b9eb-cf251c414375.png)

**Comment by andersberglund** [comment]
This one, from the Event Viewer, worked one time of four tries.

![image](https://user-images.githubusercontent.com/2539487/174496829-a36bf834-020c-4923-8efc-e332d283f4cc.png)

Program
Säkerhet
Installation

**Comment by andersberglund** [comment]
Hello

My settings page doesnt look like yours, I'm on Windows 11 Beta. But here it is.
I have tried other OCR apps I have found and they can read the text, but that is done by saving a screenshot and then loading the picture into the app.


![Urklipp-1](https://user-images.githubusercontent.com/2539487/179366809-1285c78d-dde5-4739-b0ca-487903576bfb.jpg)

**Comment by andersberglund** [comment]
Hello again

I ran TextGrab in Visual Studio debug mode and got this error:

System.Runtime.InteropServices.COMException
{"OpenClipboard Failed (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN))"}

Line 323 in fullscreengrab.xaml.cs     Clipboard.SetText(grabbedText);

Maybe this can explain why it doesn't work for me.

I changed the line to Clipboard.SetDataObject(grabbedText); as recommended by several sources.
So far it is working 👌

**Comment by TheJoeFin** [comment]
[This Stackoverflow answer](https://stackoverflow.com/questions/44538513/clipboard-settext-fails-whereas-setdataobject-does-not#:~:text=SetText%20%28text%29%20never%20clears%20the%20Clipboard%20when%20the,and%20SetDataObject%20%28SomeString%2C%20true%29%20to%20see%20any%20difference.) has a helpful explanation. Not sure why SetText would be crashing, but SetDataObject is working. Anyway I some testing and it is working well, Text Grab will use SetDataObject to add the text to the clipboard.

**Comment by andersberglund** [comment]
I glad it's solved, it's a great app.
