### ISSUE TITLE
[Feature Idea] Scan folder of images

### ISSUE THREAD

**Issue by astandarduser** [TheJoeFin/Text-Grab#176]
Something I've been wanting in windows for so long is the ability for something to do OCR on a massive folder of screenshots and have the ability to search for text (and show which photo the text is from). I'm guessing this may be out of the scope of this project but just wanted to check.

A simple way to do it would be like share-X where when you press the OCR button it generates a text file with the same name as the image which has the OCR text inside. Super useful as windows general search can read within a text file

 Also is it possible to change it to a mode where it maintains a table structure for text if the photo has it in a table layout

**Comment by TheJoeFin** [comment]
I really like this idea, but I am not sure about creating .txt files for each image. Maybe if I figure out tying into the Windows right-click context menu then that could be an option. 

But for now, similar to how the Edit Text Window has the option to list files and folder names from a directory; adding the ability to scan images and bring the text into the ETW would also be handy.

Also maybe if Text Grab did make .txt files for each image, it would append the date/time on the file name to make it clear this image to OCR process happened once.

**Comment by astandarduser** [comment]
Would be super useful, but yes having a .txt file for each picture would create a lot of clutter. Maybe an individual text file per folder which stores all necessary info for each image in the folder wouldn't be so bad. I think the scan shouldn't happen for every photo on the PC but rather only for folders specified by the user

**Comment by TheJoeFin** [comment]
@astandarduser this was actually a very easy feature to build in to the Edit Text Window and I have done so. If you build the code yourself you could have it working today, otherwise you will have to wait until the next release.

![image](https://user-images.githubusercontent.com/7809853/178509421-0764dc3b-96bb-47bf-bbbc-500255e18dc4.png)

**Comment by astandarduser** [comment]
Woah, thank you so much for implementing that. Unfortunately I don't have the knowhow to build it but I'll keep an eye on the releases

**Comment by TheJoeFin** [comment]
I appreciate the idea! Stay tuned I will probably be releasing soon with other features I'm working on

**Comment by vivadavid** [comment]
Hi! This is a great feature!

I was wondering if Text Grab could also search for images in subfolders inside subfolders, etc, as deep as possible. Also, it'd be great if this option could enable or disable as needed by the user.

Thanks!

**Comment by TheJoeFin** [comment]
@vivadavid I did not make the image reading recursive on purpose because of possible scenarios where Text Grab is processing for a very long time. I plan to rework the method to allow for safe cancelation. I will make a new issue to track this work.

@astandarduser This feature is in the 2.7 release now available.

**Comment by vivadavid** [comment]
> @vivadavid I did not make the image reading recursive on purpose because of possible scenarios where Text Grab is processing for a very long time. I plan to rework the method to allow for safe cancelation. I will make a new issue to track this work.
> 
> @astandarduser This feature is in the 2.7 release now available.

That would be great! Thank you, @TheJoeFin !

**Comment by astandarduser** [comment]
Have just tested the new update and it's great. The only thing that would make the folder scan even better is the ability to right click in the area of the located text and have the option to: open the file, and open file location (open the folder) while selecting that particular file so you don't have to navigate to it. 

Not sure if that would be doable, I guess it would just need to find the nearest filename above the clicking point along with it's origin folder (stored at the top) (you'd probably have to change the filename format so it's easy to find)

Also I am scanning a folder with 15k pictures so it did take a while but I noticed the scan used barely any CPU, if it's possible to increase/decrease the CPU usage when performing the OCR that would be amazing although not sure if Microsoft will give that option

**Comment by vivadavid** [comment]
Hi, @TheJoeFin ,

Thank you for implementing recursive search for folders.

I can't find, though, a way to just perform OCR on a single image.

Another addition, although it's not that important to me, would be a way to perform OCR on the images inside a folder, without the recursive part. If both options (with or without recursiveness) can't be available, I'd prefer keeping it recursive.

Thanks again and I wish you a great 2023!

**Comment by TheJoeFin** [comment]
Happy New year @vivadavid 
I am assuming you are in the Edit Text Window and clicking "Extract Text From Images in Folder..." from the Capture menu. After clicking that option there is a window which asks if you want to do recursion or not. 
---------------------------
OCR Options
---------------------------
Would you like to OCR images in every sub-folder?
---------------------------
Yes   No   Cancel   
---------------------------

To OCR a single image, just drag and drop it on the Edit Text Window text area or copy the image and select "OCR Paste" from the File menu (hot key ctrl + shift + v)

Does that answer your question?

**Comment by vivadavid** [comment]
Thank you for quick reply, @TheJoeFin 

1. As for the recursive mode, I forgot there was a pop-up window. I should have double-checked before asking: sorry.
2. As for an individual image, drag and drop works, but "OCR paste" (which I found on the Edit menu) is off (I had previously clicked on "Copy" on File Explorer).  Is there something I missed?

**Comment by TheJoeFin** [comment]
@vivadavid I have investigated and fixed the issue with OCR Paste not enabling and that will be in the next release. I appreciate the feedback keep it coming! :)

**Comment by vivadavid** [comment]
> @vivadavid I have investigated and fixed the issue with OCR Paste not enabling and that will be in the next release. I appreciate the feedback keep it coming! :)

Thank you, @TheJoeFin  !
