### ISSUE TITLE
Launching the 3 modes separately?

### ISSUE THREAD

**Issue by fhtdtdj** [TheJoeFin/Text-Grab#181]
Apologies if I missed it but is there a simple way to launch the 3 modes separately?

You may define the default launch mode in the settings, and define hotkeys to switch between the 3 modes.
But the hotkeys will only work if the process is already in the background.

Since there's only one .exe (portable version), would creating a shortcut and adding the -mode after the .exe be feasible perhaps? As in:

Text-Grab.exe -editor
Text-Grab.exe -fullscreen

Additional suggestions for the editor:
- an option to always remember last used window position/location/if always on top was enabled; as it resets every time you close and relaunch the program.
- ability to drag and drop multiple images perhaps? Currently limited to one drop at a time.

**Comment by TheJoeFin** [comment]
Hello @fhtdtdj 

For launching each mode separately.
1. Right click the shortcut when pinned to the Taskbar or Start Menu
2. Adding arguments to a shortcut is possible today, and is actually the same way JumpLists work. I just tested it:

![image](https://user-images.githubusercontent.com/7809853/188221469-02affdce-5bf7-43c0-98e7-1040f753b6eb.png)
 
To see what to enter as arguments check out this portion of App.xaml.cs here:
https://github.com/TheJoeFin/Text-Grab/blob/d3dd4cd2410406f16637e9c8af9e3be94e0011d2/Text-Grab/App.xaml.cs#L59-L96

As for the additional suggestions I think they are good enough to deserve their own issues.

**Comment by fhtdtdj** [comment]
Perfect. Perhaps adding a mention of this on the main page would be useful, as it doesn't seem to be documented for average users? I'll close and open the other suggestions as separate issues if you prefer.
