### ISSUE TITLE
Editor: scanning content via CLI? (TextGrab.exe + "%path")

### ISSUE THREAD

**Issue by fhtdtdj** [TheJoeFin/Text-Grab#184]
Unless I'm mistaken, currently, the way to scan a file is by manually imputing a file path from within the editor, either as "open file" or via drag and drop onto the window.

Is there or could there be a way to open a file path externally (such as command line, which could then be used to create a custom context menu item...)?

For files: running textgrab.exe "%filepathtoimage\image.jpg" opens the image in the editor indeed, but reads *the image's actual file code itself*, displayed as gibberish, like when you open a .jpg in a regular text editor. Instead of scanning the text within it.

Additionally, a similar way to scan a file, and copy its content directly to clipboard. Running a command such as textgrab.exe -copytoclipboard "%filepathtoimage\image.jpg"

For folders: running textgrab.exe "%folderpath\" could output the scanned content of the folder as "folder_OCR.txt" or whatever.

I don't use the native Windows file manager but Directory Opus, which lets users create/customize context menu items with CLIs. What I'd like to do:
Right-click a file, "scan OCR", it opens the editor with the text content!
Right-click a file, "copy OCR", it copies content to clipboard!
Right-click a folder, "scan OCR", a .txt is automatically generated!

Hope it makes sense. This would be a killer feature taking textgrab to the next level I think.

(mentioned this in https://github.com/TheJoeFin/Text-Grab/issues/179 / sorry to keep creating new issues but I figured you'd prefer separate suggestions)

Side question but...: will textgrab remain a separate program or will it get merged into powertoys? I'm surprised MS hasn't already added something like this?

**Comment by TheJoeFin** [comment]
I think it would be very possible to improve the CLI capabilities of Text Grab. These all seem like good suggestions to me.

As for Text Grab getting added to PowerToys, I wrote Text Extractor for PowerToys which is just the "Fullscreen Grab" mode of Text Grab. I will still be working on Text Grab and doing more experimentation to find what is actually useful.
