### ISSUE TITLE
Arabic Language in Win 11

### ISSUE THREAD

**Issue by Mrheshamkamal** [TheJoeFin/Text-Grab#185]
When I used Win 10 on my PC, I was able to switch the recognition language after changing the keyboard layout from En. to Ar. , vice versa. 
Now I have upgraded my Win system to Win 11, and even if I switch the keyboard language to Ar. before starting the Text-Grab App, the recognition language doesn't change to any other language than English. Is there any solution for this? Thanks.

**Comment by ArielAssaf** [comment]
I am also unable to switch to Hebrew. Is it a right to left language thing? Thanks for the amazing work!

**Comment by TheJoeFin** [comment]
@ArielAssaf can you be more specific. What mode are you using? What languages do you have installed on your computer?

**Comment by Mrheshamkamal** [comment]
Thank you, Joseph for this wonderful tool. I have figured out that I had to install Ar language keyboard after upgrading to win 11, the choice between Ar and En was available in your wonderful app after I installed the Ar keyboard. Thanks. And sorry for bothering you with this post, which I closed. Thanks and best regards

**Comment by ArielAssaf** [comment]
> 

Thank you. I am on win 11. I have English and Hebrew installed. I have tried all modes, but I default to full screen. The language dropdown simply shows only English. See images. Did I miss something?

![image (1)](https://user-images.githubusercontent.com/582002/189471466-d0d19da3-b950-4600-bee7-4c5d47ffea68.png)
![image](https://user-images.githubusercontent.com/582002/189471471-0a738931-4faf-48e6-bfb6-96afab99f3e3.png)

**Comment by TheJoeFin** [comment]
I have looked into this issue, and as far as I can tell Hebrew may not be a supported OCR language on Windows. If anyone knows otherwise please comment.

**Comment by ArielAssaf** [comment]
Thank you. I am on win 11. I have English and Hebrew installed. I have
tried all modes, but I default to full screen. The language dropdown simply
shows only english.
[image: image.png]

[image: image.png]

**Comment by avipars** [comment]
Currently, hebrew isn't supported for OCR: 

https://learn.microsoft.com/en-us/windows/powertoys/text-extractor#supported-languages

You can check via powershell (elevated) 

`Get-WindowsCapability -Online | Where-Object { $_.Name -Like 'Language.OCR*' }`


if and when they add the hebrew language pack, it will show up in the list 

![image](https://github.com/TheJoeFin/Text-Grab/assets/5733247/797ff7b8-22c1-44af-8430-16b790096305)
