### ISSUE TITLE
Ideas for Text grab

### ISSUE THREAD

**Issue by RSZ-Max** [TheJoeFin/Text-Grab#186]
Thanks for a great app, it saving me lots of time. A couple of ideas that would make life even easier;
1. When using Grab Frame, once the text is selected and double clicking it which automatically copes it to the clipboard, it would be good if the text Grab window then closed.
2. Instead of using WIN+Shift+G to open a new Grab frame, it would be good if when right mouse was clicked when hovering mouse on an image if there was an option to select Text Grab from there along with the usual windows options of Save Image as, copy image etc.
Thanks

**Comment by TheJoeFin** [comment]
1. If you hit escape twice the Grab Frame is closed, I'm not sure I want to add an option to close the Grab Frame on a word double click, but if there are others who would like it, then I'll reconsider. 
2. I am not sure if there is a way to detect if the mouse is hovering over an image. That would be an awesome feature, but maybe not feasible with today's Windows APIs. If you know of a way, please let me know!
