### ISSUE TITLE
Version 2.7.1 Not Correctly Capturing Column of Numbers

### ISSUE THREAD

**Issue by GaryGraham54** [TheJoeFin/Text-Grab#194]
Not impressed with the latest version.
The previous version worked much better for me.
One example is my attempts to capture a column of numbers. 
Any single-digit number is ignored and not captured. 
Only two digits and above are captured.

**Comment by TheJoeFin** [comment]
Hello @GaryGraham54 sorry to hear you are not getting reliable results. Please provide a screenshot of something similar to what you are trying to OCR so I can reproduce the issue on my device, and work on making an improvement.

**Comment by TheJoeFin** [comment]
@GaryGraham54 the image did not come through to GitHub, feel free to email joe@textgrab.net to connect directly on this issue.

**Comment by TheJoeFin** [comment]
![thumbnail_image](https://user-images.githubusercontent.com/7809853/198377237-ab68d498-8d47-4413-8e42-3c0847e793bc.png)

Need to test this with Tesseract and see if this is a general OCR issue or specifically related to the Windows OCR API

**Comment by TheJoeFin** [comment]
@GaryGraham54 I tested this scenario with Tesseract and did not get good results. I am thinking OCR is not well suited for this scenario. I am not sure what else I can do with Text Grab to fix this issue so I will be marking it as Won't Fix and closing the issue. If something comes up later which changes the issue can be reopened.

**Comment by GaryGraham54** [comment]
Thank you, I appreciate your efforts.
What puzzles me is that it worked flawlessly prior to that recent update.
Thanks again,
Gary

**Comment by TheJoeFin** [comment]
@GaryGraham54 the previous versions of Text Grab are still available in the GitHub releases section. Can you please retest and find which version works for you? Then I can look through the differences and hopefully find a fix. Also details about your system would be helpful such as Windows version, display scaling, and resolution.
