### ISSUE TITLE
Disable 1 of the global hotkeys

### ISSUE THREAD

**Issue by nochlab1** [TheJoeFin/Text-Grab#210]
i dont see a option to disable 1 of the 4 global hotkeys it shows either all or none how do i have that 2 global hotkeys are enabled and 2 not

**Comment by TheJoeFin** [comment]
@nochlab1 good point! I'll make it so that when you clear out the text in the hotkey box it will disable that hotkey.

**Comment by nochlab1** [comment]
Thanks so much that was fast!!

**Comment by vivadavid** [comment]
Hi,

I was going to suggest the same thing on a separate thread until I found this one.

I only use WIN+SHIFT+F as a hotkey and it would be nice if I could disable the others, just in case I need them for other programmes. Enabling and disabling each hotkey would be useful.


Thanks!
