### ISSUE TITLE
Extract from Images in Folder doesn’t output OCR

### ISSUE THREAD

**Issue by agentchimendez** [TheJoeFin/Text-Grab#214]
**Describe the bug**
Hello

I’ve just started using this app today so apologies if I’m missing something. When attempting to use the command line tool or the menu item from the text edit I cannot get “Extract Text from Images in a Folder” to output the text, it only shows file names, location and time elapsed for OCR. 

Related but needs more testing. Other command line functions do not seem to work either. Full screen command does nothing, GrabFrame and filepath show blank Edit Text window. 

**Where is the bug**
- Edit Text Window
- OCR Output
- Command Line?

**To Reproduce**
Setup: cd to appropriate folder. 
1.(a) Type “.\Text-Grab.exe “C:\Users…TagTest” in Command Prompt. 
1.(b) Open Text-Grab from Start Menu(set to open to text editor), select ‘Capture’ menu, select ‘Extract Text from Images in Folder’
2. Select folder in Windows pop up. 
3. “Would you like to OCR images in every sun-folder?” Select “Yes”(only one image in folder)
4. Wait for OCR to complete
5. Outputs image file name, “Completed OCR of 1 images”, from “C:\…”, “and took 00:00:10.69”
6. Click “Save to File” and choose location
7. Open saved .txt and see same output copied from Edit Text window. 

**Expected behavior**

From step 5 onward:

5. Outputs file name(etc) above OCR text in Edit Text window. 
6. Ditto
7. Open saved .txt and see only OCR text. Does not see file name or other information about process. 

**Screenshots**
Photo attached. Work computer vs home GitHub acct stupidness. Shows Edit Text window, command prompt and Notepad with output. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 10.0.19045 Build 19045
 - Text Grab Version 3.0

**Additional context**
Much more familiar with Linux and MacOS than Windows. Possible I did something wrong using Visual Studio for the first time. Thanks!
![image](https://user-images.githubusercontent.com/77798255/205129465-3f6637f6-be6c-42cb-90f8-40312b44caa4.jpg)

**Comment by TheJoeFin** [comment]
Hello @agentchimendez when I repeat your steps shown here, I do not have any issues. It looks like the command line arguments you entered are correct, and Text Grab is trying to OCR the images in the folder, but they do not contain text which could be extracted. 

The command line arguments you entered in cmd worked for me. Such as opening a file, OCRing a directory, and opening a Fullscreen Grab.

If Text Grab cannot extract text from an image it will just list the file name, but nothing below. Are you sure there is legible text within IMG_6758.jpg? Another way to test this is to drag and drop the image onto the Edit Text Window. This will OCR the image and add any extracted text.

Another thing you can do is to download some of the test images from this repository such as this one:
https://github.com/TheJoeFin/Text-Grab/blob/main/Text-Grab/Images/FontTest.png
and put it within the TagTest folder. Then run the command line arguments and see if that image is correctly OCR'd.

Let me know if you are still having issues.

**Comment by agentchimendez** [comment]
That was a great help!

It looks like the OCR doesn't deal well with blank space and cropping my input images is what was needed. The test image let me know it's working so thanks for that in particular.

I guess figuring out how to script image cropping is the next step! Thanks!

I've attached an example of what worked and what didn't for anyone else that might be searching around this type of problem. 

![CroppedWorking](https://user-images.githubusercontent.com/77798255/207305366-d974c9bd-2491-44e8-bdf2-fa84bab1ad46.jpg)
![UnCroppedNotWorking](https://user-images.githubusercontent.com/77798255/207305371-dd07939b-f0c0-4ac0-8112-4c463c118e4e.jpg)
