### ISSUE TITLE
PowerToys?

### ISSUE THREAD

**Issue by mahengrui1** [TheJoeFin/Text-Grab#218]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Maybe you can mention PowerToys uses your contribution.

**Comment by mahengrui1** [comment]
Hello, I noticed now(several months ago) the PowerToys updated a message says 
>It is recommended to use the Snipping Tool instead of the TextExtractor module

Do you have any comment? For me, I have seen that Snipping Tool has a larger minimum area requirement to OCR

**Comment by TheJoeFin** [comment]
Text Extractor is not going away, but I am not investing development time into it. Text Grab is going to be around forever and I am actively working on new features.
