### ISSUE TITLE
Request for OCR to support Thai language

### ISSUE THREAD

**Issue by Kuju29** [TheJoeFin/Text-Grab#224]
I'm using query for OCR language packs but I can't find TH or Thai language, is it possible you can add it.
thank you very much. 🙏😅

**Comment by TheJoeFin** [comment]
Hello @Kuju29 thank you for the issue. Unfortunatly I cannot add additional OCR languages, but I am going to add support for Tesseract (by Google) which has support for more languages. I am going to close this issue, but keep an eye on #209 for updates.
