### ISSUE TITLE
Option for Grab Frame to recognize content on the button click

### ISSUE THREAD

**Issue by GeniusBroccoli** [TheJoeFin/Text-Grab#226]
Grab Frame (I use Edit Text Window mode) starts capturing content immediately after being opened. Is it possible to make the option of capturing on the button, so that you can first place the window in the desired position.

**Comment by TheJoeFin** [comment]
I agree something needs to be tweaked to make the Grab Frame less awkward. When you say it should not capture content, do you mean:
1. It should not be sending the text to the Edit Text Window
2. The Grab Frame should not analyze at all until triggered

Thank your feedback.

**Comment by GeniusBroccoli** [comment]
I think second variant would be better.

> 2\. The Grab Frame should not analyze at all until triggered

**Comment by TheJoeFin** [comment]
@GeniusBroccoli please download and try v3.2.0-preview1 and let me know if the Grab Frame options are improved to your liking.

https://github.com/TheJoeFin/Text-Grab/releases/tag/v3.2.0-preview1

**Comment by GeniusBroccoli** [comment]
> @GeniusBroccoli please download and try v3.2.0-preview1 and let me know if the Grab Frame options are improved to your liking.
> 
> https://github.com/TheJoeFin/Text-Grab/releases/tag/v3.2.0-preview1

So, as far as I understand, the new option is called Auto Start OCR. When disabled, the text is not recognized. And to start I need to press the Refresh button (Ctrl+R). I think I'm happy :D. Thx.

**Comment by TheJoeFin** [comment]
@GeniusBroccoli yep that is how it works, I'm working on improving the UI to show a button when that option is checked to highlight that the behavior is different.
![image](https://user-images.githubusercontent.com/7809853/212385548-50775e6a-dd4f-4cef-8560-3a880f4df283.png)
