### ISSUE TITLE
Full Screen Grab doesn't run correctly on multiple monitor setup

### ISSUE THREAD

**Issue by mdzwzw** [TheJoeFin/Text-Grab#248]
**Describe the bug**
I have four monitors and when I run the Full Screen Grab, it runs just on three monitors.

**Where is the bug**
- Fullscreen Grab

**Comment by TheJoeFin** [comment]
Hello @mdzwzw, please download Text Grab 3.2.0-Preview1 and test to see if that solves the issue.

**Comment by mdzwzw** [comment]
I tested it. It has the same issue.

**Comment by TheJoeFin** [comment]
please provide screenshots of your display arrangement. See #228 for example

**Comment by mdzwzw** [comment]
![Test](https://user-images.githubusercontent.com/75279794/212487899-2b2ad29e-ebae-4d0e-a453-d4821977883c.jpg)

**Comment by TheJoeFin** [comment]
Can you also send a screenshot of the display settings so I can see arrangement and numbering?

**Comment by mdzwzw** [comment]
![1](https://user-images.githubusercontent.com/75279794/212490255-4348b410-2105-4e52-aa27-dc88d65f2df4.jpeg)
![2](https://user-images.githubusercontent.com/75279794/212490259-e6c20c65-5229-40a8-9511-1a315809cf52.jpeg)
![3](https://user-images.githubusercontent.com/75279794/212490261-7d9afbdd-56c4-4e6b-85fb-da66fdbb0ed5.jpeg)
![4](https://user-images.githubusercontent.com/75279794/212490266-95144bf8-191c-4d44-8b7d-d526282807e0.jpeg)

**Comment by TheJoeFin** [comment]
Thank you for all of the info! I'll dig into this soon. It looks like display 1 is twice as bright, and screen 4 has no frame. Is that correct?

**Comment by mdzwzw** [comment]
I wasn't focusing on display 1 brightness, but actually, yes it is brighter than screens 2 and 3. I thought it is by default like that, if not, so it is another bug. But the main issue is that screen 4 has no frame.

**Comment by TheJoeFin** [comment]
I suspect the frame which is supposed to go to screen 4 is doubled up on screen 1.

**Comment by TheJoeFin** [comment]
@mdzwzw  I have made changes to the logic which places new Full-screen Grabs in preview2. Check it out here and let me know if this fixes the issue.
https://github.com/TheJoeFin/Text-Grab/releases/tag/v3.2.0-preview2

**Comment by mdzwzw** [comment]
![fix](https://user-images.githubusercontent.com/75279794/212501003-1d397ce9-072f-4cf8-a9c3-22723cb4cbf8.jpg)

Thanks, the issue got fixed.
