### ISSUE TITLE
closing curly braces are not recognized

### ISSUE THREAD

**Issue by humazed** [TheJoeFin/Text-Grab#252]
**Describe the bug**

**Where is the bug**
- OCR Output

**To Reproduce**
try to OCR any code with curly braces

![image](https://user-images.githubusercontent.com/8838182/213721469-1bd469fc-da00-43ab-9a6c-485d1ad71181.png)
```
the output, notice the missing closing curly braces
public class myApplicationCIass extends Application {
@Override
public void onCreateC) {
super. onCreateC) ;
// TODO Put your application initialization code here .
```

**Where did you get Text Grab?**
- Chrome, but it everywhere

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 22H2
 - Text Grab Version: 3.1.1

**Comment by TheJoeFin** [comment]
Unfortunately this issue lies with the Windows OCR Engine. There is nothing I can do to fix the poor recognition of thin, single line characters.
