### ISSUE TITLE
Capture Previously Grabbed Region

### ISSUE THREAD

**Issue by TheJoeFin** [TheJoeFin/Text-Grab#258]
When a user captures a specific area with the Full-Screen Grab there should be a quick way to repeat that grab, with the same settings and area. Handy for processing pages where repeated region selections would be handy.

**Comment by sownheard** [comment]
YES this is the exact function I'm looking for in the software

I'm trying to grab text that is commonly founded in the same spot to feed to a TTS bot so i won't have to read everything but can instead listen to the audio.

Adding the ability to repeat the last grab region would be godsent
as it would greatly reduce the amount of time wasted repeating the same task
