### ISSUE TITLE
Distinction between zeroes and O's

### ISSUE THREAD

**Issue by LivingSoul8** [TheJoeFin/Text-Grab#269]
**Describe the bug**
When extracting text from the image below I got the mentioned output, which contains some false recognitions of O's where there are zeroes.

**Where is the bug**

- Grab Frame
- OCR Output

**To Reproduce**
1. Go to 
![image](https://user-images.githubusercontent.com/128725121/227258629-fe5a90ae-a6a6-498b-974e-1e1a10d2310b.png)
2. Perform a text grab (Win+Shift+T Key)
3. Paste it in a text file.
4. It recongnizes OOAEC6F8PDNLHOBPH810UOD67A instead of 00AEC6F8PDNLH0BRH810U0D67A.

**Expected behavior**
I would have expected it to recognize the narrower shaped zeroes as zeroes and not the more round O's.

**Screenshots**
I hope the problem is quite easy to understand and reproduce and does not need screenshots.

**Where did you get Text Grab?**
- Microsoft Store via Microsoft PowerToys

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 22H2
 - The version included with the Microsoft PowerToys v0.68.1

**Additional context**
I searched all TextGrab issues using the keyword "zero" and no issues showed up, so I thought I might let you know about the problem. I'm happy that such a great tool exists. :-)

**Comment by TheJoeFin** [comment]
This is a shortcoming of the OCR engine, Microsoft has no plans to improve, and making my own engine is beyond the scope of this project.
