### ISSUE TITLE
incorrect copying

### ISSUE THREAD

**Issue by benycooler** [TheJoeFin/Text-Grab#270]
instead of some numbers - letters 4=h 9=g B=8 Can I fix it with my own hands?
![image](https://user-images.githubusercontent.com/129014775/227812630-33e4ab22-8623-4ce7-a661-ad085b8c3bdb.png)
![image](https://user-images.githubusercontent.com/129014775/227812664-d2f71695-b3d1-49d3-adde-9a29ea1d71a1.png)

**Comment by TheJoeFin** [comment]
Sometimes the OCR is incorrect, but with the Grab Frame in your screenshot, you should be able to click on the text and correct any errors. Does that work for you?
