### ISSUE TITLE
Minor issues with Tesseract

### ISSUE THREAD

**Issue by vivadavid** [TheJoeFin/Text-Grab#284]
Hi!

I'm testing version 4.0.0 preview 1 (from file _text-grab-2023-04-26.zip_) on Windows 11 (22H2) and I'm really excited about the Tesseract capabilities, especially if, as you claim, it's more accurarate than the Windows OCR tool. So far, I've found a couple of tiny issues:

1. On _Settings_ > _Use Tesseract when possible_ > _More information_, clicking on any of the three links doesn't do anything, and you can't select the text either in order to paste it on the browser (ironically, I had to take a screenshot with Text Grab to achieve this).

2. I've found a link to get an updated verion of the installer (5.3.1 instead of 5.2): https://github.com/UB-Mannheim/tesseract/wiki

I've always used Tesseract embedded in OCR programmes, so this will be my first time actually installing Tesseract. Later today, I hope to do some testing, but I wonder how I'll be able to download the language models I need (again, so far I've used the interface of the Tesseract frontends).

Thank you for making Text Grab better and better.

**Comment by TheJoeFin** [comment]
Thanks for catching these! Also I'm not very familiar with Tesseract, so I'll be interested to hear how it works for you. If Text Grab needs some different features to support Tesseract better please let me know!

**Comment by vivadavid** [comment]
Hi,

The links work now on 4.0.0 preview 2, and you have updated the second one with the latest version of the installer, but the displayed text should show:

https://github.com/UB-Mannheim/tesseract/wiki

Instead of:

https://hypi.app/assets/wp/wp-content/uploads/2019/10/wiki/

Thanks!
