### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by vivadavid** [TheJoeFin/Text-Grab#286]
Hi,

I've noticed that version 4.0.0 preview 1 comes with a new logo. Art is always subjective, but I find the new one more elegant and more pleasing to my eyes, though, at the same time, it's less descriptive, as the letter _T_ is gone. Removing the letter is surely a conscious decision and, even if I feel there's something missing as a result, I also wonder if adding the letter back would spoil the design.

![logo](https://user-images.githubusercontent.com/9334287/234878889-b77917d2-51eb-4889-96dd-22b681292507.png)

Just my two cents.

**Comment by TheJoeFin** [comment]
Thank you for your feedback, and I'll leave this issue open so others can chime in with their thoughts.

I agree the "T" was a major element of the old logo, but as I had been working through different designs and ideas it was too restrictive in a couple of different ways. Text Grab can copy more than just English text, and it is more than a text editor/processor. 
The new logo is more conceptually simple and can be used when communicating all aspects of Text Grab.
