### ISSUE TITLE
Tesseract

### ISSUE THREAD

**Issue by vivadavid** [TheJoeFin/Text-Grab#288]
Hi,

I've done some testing with Tesseract on Text Grab 4.0.0 preview 1.

1. I installed Tesseract 5.3.1 (https://github.com/UB-Mannheim/tesseract/wiki), and through the installer, I also installed the English and the Spanish trained data files.

2. I turned on the Tesseract on Text Grab.

3. I tried to take a fullscreen grab but nothing happened.

https://user-images.githubusercontent.com/9334287/235002368-18f005b0-5483-458f-94f8-5ebf98a2c71f.mp4

3. I thought Text Grab was unable to detect Tesseract and I wondered if I had made a mistake selecting _Install just for me_, so I uninstalled the Tesseract and I installed it again, this time selecting _Install for anyone using this computer_.

5. The result was the same, as seen on the previous video.

6. Then I wondered if maybe the problem had to do with the Spanish model and, on Text Grab, I selected English: this time it did perform the OCR.

Some comments (see attached file):

[tesseract_test.zip](https://github.com/TheJoeFin/Text-Grab/files/11348451/tesseract_test.zip)

1. The OCR doesn't produce a good result and there's some noise (the Microsoft OCR engine does better).

2. The OCR for English GB and the OCR for English US don't produce the same result.

3. The trained data files are quite small (3,93 MB for English and 2,18 MB for Spanish). It makes me think if the trained data files correspond to a low quality type (at least in past versions of Tesseract, there was a fast model). Through Subtitle Edit, I managed to download the Spanish trained data for Tesseract 5.3.0 and it was a 17.4 MB file.

**Comment by TheJoeFin** [comment]
There are many things which need to be done surrounding Tesseract to make it more understandable and not just fail quietly. For now I am going to add the word EXPERIMENTAL to the Tesseract toggle to highlight there will be rough edges. There are several items in this issues we'll need to break down into smaller items and plan for how to address them. That will likely be on 4.1 or later.

I appreciate you working though the details and letting me know how it is working for you. Let's use this issue as a catch all discussion for what needs to be fixed to make the Tesseract experience awesome.

**Comment by vivadavid** [comment]
I'll be glad to help, Joe.

**Comment by TheJoeFin** [comment]
From your original comment here is what might need to get done:
- Better error reporting (no silent fail)
- Validate path of Tesseract Exe
- Pick and set path of Tesseract Exe
- Only try installed Tesseract languages
- More links for downloading languages 
- Look into managing Tesseract languages via CLI
- Pick a similar language if the selected language does not match any installed language

**Comment by vivadavid** [comment]
It looks like a reasonable list.

In the best possible scenario, Tesseract would be included in Text Grab with an interface to download languages: I like the way Subtitle Edit does it, for example.

**Comment by vivadavid** [comment]
Hi,

I've been doing some research about Tesseract and I have realized that the Mannheim installer installs the fast trained data model: that's why the files were smaller. Those files can be manually replaced by the "standard" trained model, which should be more accurate and not too slow for more computers.

I have tried it and it works, but again, not with Spanish. As for English, I still prefer the Microsoft OCR tool, as Tesseract introduces more noise: yesterday, it tried to OCR the file logo on a screenshot of File Explorer, and now I can see that it sometimes fails to OCR the quotation marks.

![quotations](https://user-images.githubusercontent.com/9334287/235133563-2bb4fa41-6e93-4b4e-a9ce-fa7518fa3749.png)

**Comment by vivadavid** [comment]
Hi,

I was having a look at the new version of NormCap and it looks like what I called "noise" is produced inevitably by Tesseract, as it was conceived for printed text. This page is quite interesting and might be useful for your implemention:

https://dynobo.github.io/normcap/#faqs-improve-detection

**Comment by ayhamo** [comment]
@vivadavid Hello, can you explain more how did you get such standard trained models? 
Also, this might be out of this question context, but my interface is only showing En-us and Ar ( my keybaord), is there a way to add more languages to the list? i already downloaded theme in tessaract installer
Thanks!

**Comment by vivadavid** [comment]
> @vivadavid Hello, can you explain more how did you get such standard trained models? Also, this might be out of this question context, but my interface is only showing En-us and Ar ( my keybaord), is there a way to add more languages to the list? i already downloaded theme in tessaract installer Thanks!

Hi, the standard trained data models are here:

https://github.com/tesseract-ocr/tessdata

You download a particular language and replace your previous .traineddata file.

As for the Microsoft OCR and interface languages, you go to _Windows Settings_,  and then (I'm translating, as my Windows is in Spanish) to _Time & Language_ > _Language & Region_ > _Add a language_. 

I hope this helps.

**Comment by neilfranci** [comment]
> > @vivadavid Hello, can you explain more how did you get such standard trained models? Also, this might be out of this question context, but my interface is only showing En-us and Ar ( my keybaord), is there a way to add more languages to the list? i already downloaded theme in tessaract installer Thanks!
> 
> Hi, the standard trained data models are here:
> 
> https://github.com/tesseract-ocr/tessdata
> 
> You download a particular language and replace your previous .traineddata file.
> 
> As for the Microsoft OCR and interface languages, you go to _Windows Settings_, and then (I'm translating, as my Windows is in Spanish) to _Time & Language_ > _Language & Region_ > _Add a language_.
> 
> I hope this helps.

Hi, unfortunately, I also tried installing Vietnamese but it doesn't seem to show up in the language selection section, I tried Japanese and it is normal. Thanks for reading this!
![QFPTlNKxa0](https://github.com/TheJoeFin/Text-Grab/assets/66520542/38809345-2b68-403f-aee1-e51ba994f32c)

**Comment by TheJoeFin** [comment]
Hello @neilfranci right now the language of Tesseract follows the selected Windows language. You have to install the matching language on Windows in order to select it on Tesseract.

I plan on improving the support of Tesseract, but for now it is an experimental feature. If you have any other feedback please let me know.

**Comment by vivadavid** [comment]
I can't remember in Windows 10, but in Windows 11 is pretty easy to install a new language. I've just checked, out of curiosity, and Vietnamise is also avalaible for me on my Spanish Windows.

**Comment by neilfranci** [comment]
> Hello @neilfranci right now the language of Tesseract follows the selected Windows language. You have to install the matching language on Windows in order to select it on Tesseract.
> 
> I plan on improving the support of Tesseract, but for now it is an experimental feature. If you have any other feedback please let me know.

Oh, my bad for the confusion.
I'm talking about the Microsoft OCR, not Tesseract, cause changing the window interface language is not optimal.
I have a video to show the problems.


https://github.com/TheJoeFin/Text-Grab/assets/66520542/71a4b626-fb30-405e-a9f1-8100224d962a

You can see the Vietnamese option doesn't seem to show up.
I think I should make the new issue instead of comment this one, sorry for my mistake.

**Comment by vivadavid** [comment]
Hi, @neilfranci ,

It looks like the Vietnamese language package doesn't include OCR capabilities.

My screenshots are in Spanish, but you can see, at the bottom, that French includes _recocimiento óptico de caracteres_ (OCR):

![Configuración - 000472](https://github.com/TheJoeFin/Text-Grab/assets/9334287/bb9f24d7-9c33-403b-a427-4400905093bc)

Whereas the Vietnamese language package doesn't include it:

![Configuración - 000471](https://github.com/TheJoeFin/Text-Grab/assets/9334287/aff4b91f-5cb0-4d84-95a6-53fdee5a631a)

Maybe you could add a suggestion on the Feedback app for Windows. Or wait until Tesseract can be used with Text Grab.

Good luck!

**Comment by neilfranci** [comment]
@vivadavid Ahh, I don't see that at first. Maybe, I'll wait until Tesseract can be used with Text Grab. Thanks~!

**Comment by TheJoeFin** [comment]
@neilfranci and @vivadavid v4.1 now has Tesseract lang detection and selection. Give it a try and let me know how it works for you. I'll close this issue and break it into smaller issues for tracking
