### ISSUE TITLE
Startup on login option for all users

### ISSUE THREAD

**Issue by sebaretamozo** [TheJoeFin/Text-Grab#299]
Is there a startup on login feature for all users?

**Comment by TheJoeFin** [comment]
This is not currently possible. You could set it up manually, but currently Text Grab does not have an option to install and launch for all users by default.

**Comment by sebaretamozo** [comment]
I do this:
1) Edit "Text-Grab.dll.config" so that FirstRun:False / RunInTheBackground:True / StartupOnLogin:True
2) Put a shortcut of "Text-Grab.exe" in %programdata%\Microsoft\Windows\Start Menu\Programs\StartUp

The problem is whit multiple users. If one user dont log out of windows and other logs in, then the program dont start correctly.

Is there a better way to set it up manually? Thanks
