### ISSUE TITLE
Direct CLI clipboard capture without going through the text editor

### ISSUE THREAD

**Issue by fhtdtdj** [TheJoeFin/Text-Grab#300]
Using the Command Line Interface 

For files (using "file path")
if it is an image file it will OCR the file and place the results into a new Edit Text Window.

Improvement -> an option to directly copy the OCR text in clipboard, without opening the "Edit Text Window" and having to manually click "Copy and Close"

**Mode which would include change**
- [ ] General
- [ ] Edit Text Window

**Comment by TheJoeFin** [comment]
I like this idea and it seems simple enough to implement.

**Comment by TheJoeFin** [comment]
Related to #278 and fixed in 4.1
