### ISSUE TITLE
Folders scanning -> Optional filenames

### ISSUE THREAD

**Issue by fhtdtdj** [TheJoeFin/Text-Grab#301]
Using the "Extract Text From Images In Folder" scanning feature: if scanning multiple files, the output list will prefix each OCR result with the files' filenames as the first line. Filenames aren't part of the desirable OCR text, therefore add clutter to output list. Eg. if you're extracting OCR from hundreds of files, you then have to manually delete each first line containing the filenames. 

Improvement -> This could be made an optional toggle so users could choose if they also want to output filenames or not.

see image 
https://i.imgur.com/gtavoxf.jpg

**Mode which would include change**
- [ ] General
- [ ] Edit Text Window

**Comment by TheJoeFin** [comment]
I'll probably have to make an options Window for when triggering the scanning a directory. The different options can get more complicated for different options, so making a dialog makes sense.

**Comment by TheJoeFin** [comment]
I'm trying out adding the options as checkable menu items. So far it is working nicely.

<img width="309" alt="image" src="https://github.com/TheJoeFin/Text-Grab/assets/7809853/61001205-5fc2-4c8f-8578-d368e2589c54">
