### ISSUE TITLE
Edit Text Window -> Select All/Clear All

### ISSUE THREAD

**Issue by fhtdtdj** [TheJoeFin/Text-Grab#302]
While in the "Edit Text Window", in the right-click menu or in the Edit menu: adding "select all" and/or "clear all" options would be useful. You currently have to do it manually which can be troublesome if list is long. Most text editors have this option in menus.

**Mode which would include change**
- [ ] General
- [ ] Edit Text Window

(very minor suggestion rather than a request, but I know you prefer separate issues ; thanks for your awesome work!)

**Comment by TheJoeFin** [comment]
Good simple idea. I'll add this.

**Comment by TheJoeFin** [comment]
As I was implementing this I realized I didn't know exactly what you meant by "clear all" do you mean "select nothing" or "delete selection"?

**Comment by fhtdtdj** [comment]
I meant "deleting all" (same thing as "select all" + pressing delete).
