### ISSUE TITLE
Feature request: Digital number only option for data OCR.

### ISSUE THREAD

**Issue by Femtometer** [TheJoeFin/Text-Grab#305]
**Describe the pain point and your solution**
  I found that English OCR may fail on digitals numbers, An digital only mode maybe help.

**Mode which would include change**
- [ ] Settings Window

**Screenshots or sketches**
OCR result Example:
![image](https://github.com/TheJoeFin/Text-Grab/assets/5461891/14ba2aa6-ca39-482f-a4b1-300681e43bec)

**Comment by TheJoeFin** [comment]
What mode are you using when doing the capture? Fullscreen capture or Grab Frame?

**Comment by TheJoeFin** [comment]
If you highlight the text blocks you want you can right click and choose, "convert to number" to fix common number/letter conversions
