### ISSUE TITLE
Automatically open the Edit Text screen after a screenshot

### ISSUE THREAD

**Issue by vivadavid** [TheJoeFin/Text-Grab#308]
Hi,

After doing a screenshot, there's a Windows notification that you can click on to access the Edit Text screen of Text Grab.

I find myself opening this Edit Text screen every time that I do a screenshot, so I was wondering if an option could be enabled in Settings so that the Edit Text screen is automatically open after the screenshot, thus saving us from having to go to the notification panel, looking for the actual notification and clicking on it. This would make sense for me as the default behaviour, but I understand people use a programme in different ways, so a setting we could enable would be enough and certainly appreciated.

Thanks for considering this feature.

**Comment by vivadavid** [comment]
Hi, again,

I've been doing some more testing about the issue, trying to confirm how many clicks users would actually save by implementing my suggested feature: I've noticed that, on some occasions, you do get a notification toast, and in these cases, you only have to click once to get to the Edit Text screen.

However, most of the times, there's no notification toast and you have to go to the notification panel: in these cases, the suggested feature would save two clicks and considerably more time.

I don't know why sometimes there's a notification toast and sometimes there isn't: I haven't been able to find a pattern. I've done some testing and, using PowerToys to run Text Grab, there's a notification toast 2 out of 10 times. With the shortcut WIN+UPPERCASE+F, I've got the same results. So far, I've found it impredictable: it might just be a Windows issue.

**Comment by TheJoeFin** [comment]
I think this functionality might already exist.

If you click this button in the Fullscreen Grab toolbar:
![image](https://github.com/TheJoeFin/Text-Grab/assets/7809853/915b074e-e040-4701-8d33-eec05f1575cb)

Or press the E key while the overlay is active the "send Result to Edit Text Window" gets turned on.

Then after a successful OCR the result gets sent directly to an Edit Text Window.

**Comment by vivadavid** [comment]
Thank you for your replay.

I'd have two suggestions to make:

1. It seems you have to click on it every time you run the programme. Would it be possible to keep it enabled until you decide to manually disable it again?
2. I had had a look at the toolbar some time ago, but I had forgotten about this feature, as I always use Text Grab the same way. Could the _Send to an Edit Text Window_ be also enabled and disabled via settings?

Thanks.

**Comment by TheJoeFin** [comment]
I can make the "Open Edit Text Window" a sticky option so if it is turned on then Text Grab remembers that

**Comment by vivadavid** [comment]
> I can make the "Open Edit Text Window" a sticky option so if it is turned on then Text Grab remembers that

This would be really helpful: thank you!
