### ISSUE TITLE
Tooltip on bottom bar buttons

### ISSUE THREAD

**Issue by TheJoeFin** [TheJoeFin/Text-Grab#312]

**Comment by Talonkinkade** [comment]
JoeFin...I'm a nube...I just got thru my sophomore year in community college and would like to get better but think i could use some help seeing how github works from a Mentor-type standpoint.  Would you be interested?

**Comment by TheJoeFin** [comment]
@Talonkinkade send me an email and we can discuss

**Comment by Talonkinkade** [comment]
@TheJoeFin  I've found some resources for github, and you are super busy (obviously)...thank you for getting back with me.  I have been going at this the hard way.  I will do this part on my own and will shoot you a msg if when I have specifics.  I didn't notice your fast response; I didn't intend to .gitignore? you  :) and need to just get  time under my belt with basics.  Thanks!  (BTW, Great job with Text-Grab, I get excited to think that one day, when i grow up......
