### ISSUE TITLE
Cannot find tesseract.exe

### ISSUE THREAD

**Issue by nitincodery** [TheJoeFin/Text-Grab#324]
**Describe the bug**
Text Grab is unable to find tesseract (installed via scoop) in fullscreen grab mode.

**To Reproduce**
1. Take a fullscreen grab while tesseract option enabled.
2. Notification says "Cannot find tesseract.exe"

**Where did you get Text Grab?**
Scoop

**Desktop**
 - OS:  Windows 10
 - Version: 22H2
 - Text Grab Version: 4.0.1

**Comment by TheJoeFin** [comment]
@nitincodery did you follow the instructions to install Tesseract?

**Comment by nitincodery** [comment]
I installed tesseract via scoop, its path is different than installing the tesseract setup file, but the tesseract via scoop is in PATH environment variable.

Have you hard coded path of tesseract to look into program files or does it also look it in PATH env variable too? I guess it doesn't look it in PATH and just looks it in Program Files.

**Comment by TheJoeFin** [comment]
Text Grab looks for Tesseract in a few different possible install locations. I can look into using the PATH variables. Also I'll be adding the ability to set the Tesseract path manually: #325
