### ISSUE TITLE
[Tesseract] Some languages do not appear in the list

### ISSUE THREAD

**Issue by sn260591** [TheJoeFin/Text-Grab#352]
**Describe the bug**
See title.

**Where is the bug**
- Fullscreen Grab

**To Reproduce**
Install Tesseract with Chinese or Japanese (vertical) language data.

**Where did you get Text Grab?**
- GitHub releases
    - Exe

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H2 LTSC
 - Text Grab Version 4.1.3

**Comment by TheJoeFin** [comment]
@sn260591 how did you install the other tesseract languages?

**Comment by sn260591** [comment]
> @sn260591 how did you install the other tesseract languages?

![_](https://github.com/TheJoeFin/Text-Grab/assets/10724977/16fa4d0e-5ef4-4634-a73d-a71d5c902bdc)

**Comment by Driek123** [comment]
Adding on to this as I'm also facing issues with these east asian languages (& Korean, and the issue crops up whether it's vertical or horizontal script). Using Tesseract produces a blank list of languages in the dropdown for me & and then refuses to capture anything in full-screen (it just gets stuck asking to recapture). 

It works fine if I don't add any additional language/script data. 

Image of how the menu looks (missing language next to "Tesseract"): 

![image](https://github.com/TheJoeFin/Text-Grab/assets/16720778/e7bba0c2-511d-4dd1-bed5-88939164e49f)
