### ISSUE TITLE
Settings  doesn't open

### ISSUE THREAD

**Issue by andersberglund** [TheJoeFin/Text-Grab#355]
Latest source code, compiled ok.

System.Windows.Markup.XamlParseException: 'Provide value on 'System.Windows.Markup.StaticResourceHolder' threw an exception.'

Inner exception
Exception: Cannot find resource named 'SystemAccentColorPrimary'. Resource names are case sensitive.

    System.Windows.StaticResourceExtension.ProvideValueInternal(System.IServiceProvider, bool)
    System.Windows.StaticResourceExtension.ProvideValue(System.IServiceProvider)
    MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(System.Windows.Markup.MarkupExtension, System.IServiceProvider)

Exception thrown at:
      // No Window Found, open a new one
      T newWindow = new T();
      newWindow.Show();
      return newWindow;

**Comment by TheJoeFin** [comment]
@andersberglund what version of Visual Studio are you running? and what version of Windows are you running?

**Comment by andersberglund** [comment]
This looks like it's my bad. I copied the new source over the old and that probably clashed with something and caused the problem.
I copied the source to a new folder and it now works as supposed.

Sorry  if I gave you some unnecessary work. 🙄
