### ISSUE TITLE
adding a language

### ISSUE THREAD

**Issue by ashiqis** [TheJoeFin/Text-Grab#370]
I've been using Text Grab and it's been a game-changer for me. Love it!
I'd like to request the addition of Japanese language support in Text Grab. I often deal with it in images and apps, and having Text Grab support Japanese would be amazing.
Thaank youuuu

**Comment by TheJoeFin** [comment]
Hi there! You can add languages by adding them through Windows. Go to the Windows Language settings, Time and Language, Language and Region, then click "Add Language"
