### ISSUE TITLE
Leave a margin on the Edit Text Window

### ISSUE THREAD

**Issue by vivadavid** [TheJoeFin/Text-Grab#391]
Hi, Joe,

I wanted to suggest adding some space on the left and on the right of the Edit Text Window, so as to create margins that make reading the text more pleasing to the eyes. The way it is now, the text is too close to the borders of the screen.

Thanks for considering this!

![Leave a margin on the Edit Text Window](https://github.com/TheJoeFin/Text-Grab/assets/9334287/04a771a7-1740-4aae-8f6c-03114bf4e0cc)

**Comment by TheJoeFin** [comment]
Should be easy. Just have to figure out the best way to make it look good

![image](https://github.com/TheJoeFin/Text-Grab/assets/7809853/3136cc11-d130-4cb5-9e3b-1f17785c7d15)

**Comment by vivadavid** [comment]
Thanks! Personally I'd try to make the margins a bit smaller to fit more text in each line, while keeping some space on the left and on the right.

**Comment by vivadavid** [comment]
The new margins look great! Thanks!

P. S. I love the new settings section too!
