### ISSUE TITLE
Is there anyway to combine this program's capabilities with the translation program, DeskTranslate?

### ISSUE THREAD

**Issue by yasavvym8** [TheJoeFin/Text-Grab#400]
**Describe the pain point and your solution**

I love Text-Grab OCR and have used it for months and it works amazingly. I recently have come across a similar program that I have been using, DeskTranslate (https://github.com/DeskTranslate/DeskTranslate), and this program's goal is to translate text on your screen to other languages. Similar to Text-Grab OCR, DeskTranslate is built on Tesseract OCR UB at Mannheim (https://github.com/UB-Mannheim/tesseract). Also similar to Text-Grab OCR, DeskTranslate's functionality allows you to draw a box around text and then translate it using one of several engines, including Google Translate. Given these two programs' similarities, I was wondering if there were any ways that these two programs could be combined in any sort of way. Specifically, the grab-frame functionality of Text-Grab. I'm imagining it's utility in situations where someone is browsing a page in a different language, they could just place a grab frame over an area of their screen while reading and have the text continuously translating, with the letters/characters changing to their other-language counterparts as they grab frams. This would allow users the user the ability/option to copy and paste original text or translations as they scroll. I know next to nothing about programming or how difficult a task like this would be, but just thought I would pitch this idea in the case that the infrastructures of both programs are aligned in such a way where this would be doable. 

**Mode which would include change**
- [x] Full-screen Grab
- [x] Grab Frame
- [ ] Edit Text Window
- [ ] Quick Simple Lookup
- [ ] Settings Window
- [ ] General

**Describe alternatives you've tried or considered**

**Screenshots or sketches**

**Comment by TheJoeFin** [comment]
I'm closing this issue in favor of #223
