### ISSUE TITLE
main window not visible

### ISSUE THREAD

**Issue by arunsaispk12** [TheJoeFin/Text-Grab#406]
**Describe the bug**

**Where is the bug**
- Tray Icon
- Settings Window

**To Reproduce**

**Expected behavior**

**Screenshots**

**Where did you get Text Grab?**
- Microsoft Store
- GitHub releases
    - Exe
    - Self-contained

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11
 - Version [
 -  21H2

**Additional context**

**Comment by TheJoeFin** [comment]
I believe this is a bug with WPFUI and I'll be pushing an update very soon. Where did you get Text Grab from?

**Comment by arunsaispk12** [comment]
Thank you for your response

**Comment by TheJoeFin** [comment]
Is the issue solved?

**Comment by arunsaispk12** [comment]
First i would like to Appreciate you to get your work done successfully,
Iwas actually googling for text extraction software by that time I just saw
that one Text Grab Git Repo Link Then I explored the Repository and Gave it
a try also, then I start to use software it works fine but No Main window
or Settings page is visible and accessible, then I Reported it

**Comment by TheJoeFin** [comment]
@arunsaispk12 is this still an issue?
