### ISSUE TITLE
Encoding problems with extended characters via Tesseract

### ISSUE THREAD

**Issue by vivadavid** [TheJoeFin/Text-Grab#409]
**Describe the bug**
When performing OCR via Tesseract on text with extended characters, the result has encoding problems.

**Where is the bug**
- OCR Output

**To Reproduce**
1. Go to _Fullscreen Grab_.
2. Click on _spa with Tesseract_.
3. Select text that contains extended characters (_á_, _é_, _í_, _ó_, _ú_).

**Expected behavior**
The extended characters should be encoded and displayed properly, and yet, there are problems, for example, with Spanish characters carrying an accent (á, é, í, ó, ú), so that instead of getting _carácter estratégico_, you get _carÃ¡cter estratÃ©gico_.

**Screenshots**
This is the link to the original web [article](https://www.elmundo.es/economia/empresas/2023/12/19/6581cad6fc6c8368788b457f.html).

Screenshot of a passage of the web article:

![screenshot](https://github.com/TheJoeFin/Text-Grab/assets/9334287/902b9632-3827-44be-a722-5b0d6a7249db)

Screenshot of the text recognized via Windows OCR:

![OCR_Windows](https://github.com/TheJoeFin/Text-Grab/assets/9334287/ae63c21b-1d18-4e97-89a1-fd9e6091292d)

Screenshot of the text recognized via Tesseract:

![OCR_Tesseract](https://github.com/TheJoeFin/Text-Grab/assets/9334287/7532721a-29c5-4066-b8fe-2f2baabb4ec7)

**Where did you get Text Grab?**
- GitHub releases
    - Exe

**Desktop (please complete the following information):**
 - OS: Windows 11.
 - Version:  23H2.
 - Text Grab Version: 4.3.0.

**Comment by vivadavid** [comment]
I take the opportunity to wish you, @TheJoeFin, and everybody a merry Christmas and a happy New Year.

**Comment by vivadavid** [comment]
Hi, @TheJoeFin,

I can confirm that character encoding works now on version 4.3.1: thanks!

**Comment by vivadavid** [comment]
Sorry, I've just noticed that if you use the tool _Extract Text from Images in Folder_, the encoding problems are still there. I've done the following testing:

1. I've placed two images in a folder and I've run the tool. The result is that Tesseract doesn't work on image1.jpg (there's no recognized text), though it does work on image2.jpg, but with encoding problems.
2. However, if I drag these two images on the _Edit Text Window_, Tesseract works on both images and there are no encoding problems.

[images.zip](https://github.com/TheJoeFin/Text-Grab/files/13853039/images.zip)

By the way, I had always run the tool on a folder containing plenty of images, so I had never noticed the following message due to the window scroll as the text is generated:

_Tesseract can only run single threaded,
May be slower if processing many images
Press Escape to cancel_

I suggest displaying this message in a different way, so that it can be actually read by the user. One possibility could be showing up a little pop-up window before proceeding, with a button to be ticked not to display this message again.

**Comment by vivadavid** [comment]
Hi, again,

It's weird, but the problems I had with Tesseract on _Fullscreen Grab_ are back: maybe I didn't check it out properly when I wrote my first message earlier today.

So, to sum up, and with my OCR settings on _Spa with Tesseract_, the situation rests like this:

1. There are problems with both _Fullscreen Grab_ and _Extract Text from Images in Folder_.
2. There are NO problems when I drag some images on the _Edit Text Window_.

**Comment by vivadavid** [comment]
Hi, @TheJoeFin ,

Before I posted my messages the other day, I made sure that I was running the latest version (4.3.1), but I've doubled-checked, just in case, and it's indeed 4.3.1.

Just to try something else, I've deleted the settings file (user.config). I couldn't find it in the same folder as the executable, but I eventually found it here:

C:\Users\UserName\AppData\Local\Text_Grab

(By the way, if your intention is to make Text Grab completely portable, I'd suggest keeping the settings file on the same folder as the executable, where it can be easily accessible in case you want to read it, copy it or delete it.).

Unfortunately, the problems persist after this last action.

1. Would you like me to send you my settings file? I'd prefer to use the e-mail for that.
2. Do you have Tesseract 5.3.3 from Mannheim (tesseract-ocr-w64-setup-5.3.3.20231005.exe) installed on your PC?
3. In your own testing, did you try the Spanish language?

By the way, as usual, I'm running the executable file (NOT the self contained or the Windows Store versions).

Please let me know if there's something else I can do. My Tesseract installation is brand new and my language packages were downloaded through the installer, so this should be fine.

I hope I haven't done anything weird by mistake which might cause you to waste time on this issue.

Thank you for your time!

**Comment by TheJoeFin** [comment]
@vivadavid I updated the files in the release. Try those new files and see if that fixes it for you. I think there was an error in building on different branches some had some fixes.

**Comment by vivadavid** [comment]
Thank you, @TheJoeFin : the Unicode problems seem to be fixed now!

Unicode problems aside, I still detect the same other issue I mentioned earlier regarding _Extract Text from Images in Folder_:

1. On _Image1.jpg_ (see attached ZIP file), no text is recognized (but it's recognized when I drag and drop the image).
2. On _Image2.jpg_, the text is recognized, but it's not exactly the same text recognized when I drag and drop the image.

Should I open a separate page?

Thanks again for fixing the Unicode issue!

**Comment by TheJoeFin** [comment]
Great! Yeah, open a new issue and include the sample photos if you can.

**Comment by vivadavid** [comment]
> Great! Yeah, open a new issue and include the sample photos if you can.

I've just done it!
