### ISSUE TITLE
Screen Capture Issue

### ISSUE THREAD

**Issue by tim103117** [TheJoeFin/Text-Grab#410]
**Describe the bug**
When I run the app, the screen turns entirely white, making it impossible to capture anything.

**Where is the bug**
- Capturing Screenshot with this app
- Same problem with the screen recording mode of Windows Snipping Tool.

**To Reproduce**
1. Run the app 'Text-Grab.exe'
2. The screen turns white, leaving only the app's toolbar at the top and Windows Notification Toast visible.
3. Only able to capture Windows Action Center, Notification Center, and Toast Notifications.

**Expected behavior**
The white area shouldn't appear when capturing the screen.

**Screenshots**
![screenshot](https://github.com/TheJoeFin/Text-Grab/assets/98317050/9640bf34-41c2-46f6-aeea-38bd1d61b60e)

**Where did you get Text Grab?**
- Releases (27) --> Text Grab 4.3 --> 'Text-Grab.exe'

**Desktop :**
 - OS: Windows 11
 - Version 23H2 22631.2861
 - Text Grab Version 4.3

**Additional context**
PowerToys v0.76.2 is also installed, same problem when using the OCR function recently.

**Comment by TheJoeFin** [comment]
This is frequently caused by the app Mica For Everyone. Do you have that program installed?

**Comment by tim103117** [comment]
Yes, I do have Mica For Everyone installed. I changed the Global Rule > Backdrop Type to Default and that resolved the issue. Big thanks for sharing the fix!
