### ISSUE TITLE
Copies Cyrillic text with latin characters

### ISSUE THREAD

**Issue by sitex** [TheJoeFin/Text-Grab#420]
**Describe the bug**
Copies Cyrillic text with Latin characters.

**Where is the bug**
- OCR Output

**To Reproduce**
1. Switch language to "Russian"
2. Grab a frame with Russian text. Like this:
> ЭТО ТЕСТОВЫЙ ТЕКСТ ДЛЯ КОПИРОВАНИЯ В ПРОГРАММУ
3. All Cyrillic letters are written with Latin characters
> 3ТО ТЕСТОВbN TxсT AnR KОnNРОВАНNR В nРОrРАММУ

**Expected behavior**
To get this line in OCR Output with Cyrillic characters
> ЭТО ТЕСТОВЫЙ ТЕКСТ ДЛЯ КОПИРОВАНИЯ В ПРОГРАММУ

**Screenshots**
![image](https://github.com/TheJoeFin/Text-Grab/assets/140727/fb8783fe-9079-448a-b6e9-9dd4a7622153)

**Where did you get Text Grab?**
- GitHub releases
    - Exe

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 19045
 - Text Grab Version 4.3.1

**Additional context**
 - Russian Language Pack installed (including Russian OCR component)

**Comment by sitex** [comment]
And this menu bar is not working
![image](https://github.com/TheJoeFin/Text-Grab/assets/140727/e157e0fa-cee4-4c76-999f-1564b871f49e)

When I choose Russian in the menu the result text is wrong:
"3ТО ТЕСТОВbN ТЕKСТ AnR KОnNРОВАНNR В nРОrРАММУ"

**Comment by TheJoeFin** [comment]
@sitex check this setting in Settings under the general page:
<img width="505" alt="image" src="https://github.com/TheJoeFin/Text-Grab/assets/7809853/faf6da70-4d4b-4590-9d34-f1ed58bc6ba1">

**Comment by sitex** [comment]
![image](https://github.com/TheJoeFin/Text-Grab/assets/140727/2c6c5948-601c-4632-a63d-15b20a1cc20d)

![image](https://github.com/TheJoeFin/Text-Grab/assets/140727/2ce3e7f3-47fc-4f7c-8c2d-05bc9176632d)

![image](https://github.com/TheJoeFin/Text-Grab/assets/140727/39ed60af-92f9-4c8e-9526-0bfd17f98ec4)

![image](https://github.com/TheJoeFin/Text-Grab/assets/140727/2d4bc004-f7b4-4fc4-af51-6377a8d8097c)

And the result is the same:
> 3ТО ТСТОВbN ТЕKСТ AnR KОnNРОВАНNR В nРОrРАММУ

**Comment by sitex** [comment]
### Finally I have found the solution!
1. Download the latest version of the software
2. Reset All Settings
3. It's working with Cyrillic symbols
> ЭТО ТСТОВЫЙ ТЕКСТ ДЛЯ КОПИРОВАНИЯ В ПРОГРАММУ

**Comment by TheJoeFin** [comment]
@sitex can you share what value was set for the setting I have highlighted in the previous comment?

**Comment by sitex** [comment]
@TheJoeFin It was unchecked by default. And it's working this way.
No need to check this setting.

Another feedback about the mentioned setting. 
When I grab a screenshot with mixed languages it works better without that setting checked.

By default the software successfully detected Cyrillic and English characters on the same screenshot.
With this option checked the software converted all characters to the same language.
