### ISSUE TITLE
Can't turn on option «Enable Tesseract within Text Grab» - it automatically turns off

### ISSUE THREAD

**Issue by morozover** [TheJoeFin/Text-Grab#448]
**Describe the bug**
Can't turn on option «Enable Tesseract within Text Grab» - it automatically turns off

**Where is the bug**
- Settings Window

**To Reproduce**
1. Install Tesseract 5.3.3 on Windows (https://github.com/UB-Mannheim/tesseract/wiki)
2. Place eng.traineddata to \tessdata\ folder
3. Try Tesseract via CLI - it works correctly
4. Open Settings of Text Grab, than Tess section
5. Specify path to tesseract.exe
6. Turn on option «Enable Tesseract within Text Grab»
7. Switch to other section (for example Langs)
8. Switch to Tess section
9. Option «Enable Tesseract within Text Grab» is turned off

**Expected behavior**
Option «Enable Tesseract within Text Grab» stays turned on and doesn't turn off 

**Screenshots**
See GIF
![12345](https://github.com/TheJoeFin/Text-Grab/assets/17902666/437a5083-09a6-4058-8310-f2a6fa8cd123)

**Where did you get Text Grab?**
- GitHub releases
    - Exe

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 64 bit
 - Version: 22H2
 - Text Grab: 4.4.0

**Comment by TheJoeFin** [comment]
@morozover this does seem like a bug. For now I think a workaround might be:

- Enter the path of Tesseract.exe
- Close settings window
- Open settings window
- Enable Tesseract

Let me know if that does the trick or not.

**Comment by morozover** [comment]
It doesn't work

Steps:
1. Enter the path of Tesseract.exe
2. Close settings window
3. Open settings window
4. Bug: The path field is empty

**Comment by TheJoeFin** [comment]
Found a bug. Fix should be coming soon. Thank you for reporting!
