### ISSUE TITLE
Some settings are not saved

### ISSUE THREAD

**Issue by sn260591** [TheJoeFin/Text-Grab#450]
**Describe the bug**
Some settings, such as reading barcodes and saving history, are reset to default after closing the settings window.

**Where is the bug**
- Settings Window

**To Reproduce**
1. Disable reading barcodes or saving history
2. Close the settings window
3. Open the settings window

**Where did you get Text Grab?**
- GitHub releases
    - Exe

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H2 LTSC
 - Text Grab Version 4.4.0

**Additional context**
Other settings (theme, tesseract) are not affected by this issue.

**Comment by TheJoeFin** [comment]
Tested and found the bug. Fix should be coming soon!
