### ISSUE TITLE
Please add the feature to ocr-translate text.

### ISSUE THREAD

**Issue by Eirhey** [TheJoeFin/Text-Grab#454]
Please add the feature to ocr-translate text...

like how the android app "google translate" uses the camera to translate by overlaying the original text with the translated text but instead without having to use a camera & or external device to ocr translate text
![google-translate-example](https://github.com/TheJoeFin/Text-Grab/assets/136591195/e3fd3ad1-e39b-418d-b379-ecbfd7a13dd1)
...

**Mode which would include change**
- [ ] General

**Comment by TheJoeFin** [comment]
This is something I'm looking into. Captured here #223
