### ISSUE TITLE
Does not work with Rectify11 | Gray Screen

### ISSUE THREAD

**Issue by Rajdave69** [TheJoeFin/Text-Grab#457]
**Describe the bug**

When I install rectify11 and try to use this tool, upon using the full screen thing the whole screen becomes gay with the popup on top of it. It seems to have problems freezing the screen and ends up with a greyish-gradient

**Where is the bug**

- Fullscreen Grab

**To Reproduce**
1. Install rectify11
2. try to do a full screen text grab

**Expected behavior**
for the screen to be frozen as it is, and not a gray screen

**Screenshots**
![image](https://github.com/TheJoeFin/Text-Grab/assets/86198810/bef9ff0a-c7cc-429c-9825-7200b5f43e0e)

**Where did you get Text Grab?**
- choco

**Desktop (please complete the following information):**
 - OS: Windows 11 
 - Version 10.0.22631
 - Text Grab Version: 4.4.1

**Additional context**

**Comment by TheJoeFin** [comment]
Some of these tools add an acrylic or mica background to transparent windows. Text Grab uses transparent windows which might be why this is happening. Does this happen with the Grab Frame as well?

**Comment by aminitail** [comment]
![Snipaste_2024-05-15_01-50-59](https://github.com/TheJoeFin/Text-Grab/assets/42804067/440e0e60-72b4-44b2-adca-64f902aa9018)

It also happens with the Grab Frame in my case.

OS: Windows 11
Version 10.0.22631
Text Grab Version: 4.4.2

**Comment by TheJoeFin** [comment]
These tools modify windows and force any transparent window to be Acrylic or Mica. Try excluding Text-Grab.exe from these utilities

**Comment by aminitail** [comment]
That works. Thank you.

The only thing I did was to add a new rule for Text-Grab.exe on MicaForEveryone.

**Comment by dokmadrasti** [comment]
nu u menya bopshe ne roboatet, pomogite eti zapustit na rabotu
