### ISSUE TITLE
Please implement a way to remove hotkey bindings

### ISSUE THREAD

**Issue by DeadManBrooding** [TheJoeFin/Text-Grab#461]
I can only overwrite set hotkey bindings, not remove them. It says in the window "clear text to disable hotkey", but that doesn't mean anything. There's no way to clear anything in that window.

**Comment by TheJoeFin** [comment]
I do need to update that text, but you can just toggle the hotkey off with this toggle:
![image](https://github.com/TheJoeFin/Text-Grab/assets/7809853/9e7585a3-8660-4c57-a323-f165859369c4)
