### ISSUE TITLE
.NET Desktop Runtime already installed, but still can't run program

### ISSUE THREAD

**Issue by gylotip** [TheJoeFin/Text-Grab#464]
**Describe the bug**
I downloaded the latest version of Text-Grab v4.4.2 and .NET 8.0 Desktop Runtime v8.0.6, but the program still won't run.

**Where is the bug**

- Running the program

**To Reproduce**
1. Go to the download page of Text-Grab and .NET Desktop Runtime
2. Download them
3. Run Text-Grab.exe
4. Error code: "You must install .NET Desktop Runtime to run this application. —> Download it now. You will need to run the downloaded installer"

**Expected behavior**
The program should run when clicking on the executable.

**Screenshots**
<img width="482" alt="image" src="https://github.com/TheJoeFin/Text-Grab/assets/117411765/f8926831-69de-4abc-9b52-a8499aaa0847">

<img width="406" alt="image" src="https://github.com/TheJoeFin/Text-Grab/assets/117411765/3ec85765-9f12-4a3c-9573-a50750e30dc8">

**Where did you get Text Grab?**
- GitHub releases
    - Exe

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 22H2
 - Text Grab Version v4.4.2

**Additional context**
Even if .NET Desktop Runtime is installed, I still can't run Text-Grab.

**Comment by TheJoeFin** [comment]
@gylotip I can look into why that might be happening, in the mean time have you tried running the Self-Contained build? That might work better because it is not runtime dependent.

**Comment by gylotip** [comment]
@TheJoeFin Okay, the Self-Contained build is working. Thank you for your help.
