### ISSUE TITLE
About this topic: Use new Windows OCR models?

### ISSUE THREAD

**Issue by zydjohnHotmail** [TheJoeFin/Text-Grab#474]
Hi,
I found you had an issue at #470: 
https://github.com/TheJoeFin/Text-Grab/issues/470
I found that was indeed interesting, and I want to know if you know how can I use the new OCR engine for WinForms app project or other platform like WinUI?
If yes, can show share some code or provide some general instructions?
Thanks,

**Comment by TheJoeFin** [comment]
I don't know how to use the new models yet, I think the Copilot Runtime is not yet released. I will update #470 when I made updates or changes on this topic.
