### ISSUE TITLE
Bad text recognition

### ISSUE THREAD

**Issue by Zio3D** [TheJoeFin/Text-Grab#479]
**Describe the bug**
Does not correctly understand the text of the Ubuntu server console.
![Image for the OCR](https://github.com/TheJoeFin/Text-Grab/assets/42025157/a7c6bb50-4024-4342-bc5c-88b6d8725eca)

**Where is the bug**

- Grab Frame

**To Reproduce**
Grab Frame on the image attached

**Expected behavior**
That all characters are recognized correctly as there is no video interference that distorts the text or creates ambiguity about the characters.

**Screenshots**

**Where did you get Text Grab?**
- GitHub releases
    - Exe

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version: 22H2 (19045.4529)
 - Text Grab Version: 4.5 (bed6db1)

**Additional context**

**If I OCR the attached image (I opened it with Microsoft Paint of Windows 10 Pro) with zoom at 100%, I get the following text:**
```
[ CIK ] Reached target System Power Off.
[ 1745.141662] sgstemd-shutdown [1] : Haiting for process: java
```

**If I OCR the attached image (I opened it with Microsoft Paint of Windows 10 Pro) with zoom at 200%, I get the following text:**
```
[ OK ] Reached target System Power off.
[ 1745.141662] sgstemd-shutdau-lr-l [1] : Hai ting far pracess: java
```

**The correct text is:**
```
[ OK ] Reached target System Power Off.
[ 1745.141662] systemd-shutdown [1]:  Waiting for process: java
```

With the comand: `Get-WindowsCapability -Online | Where-Object { $_.Name -Like 'Language.OCR*' }`, I have these languages ​​installed:
```
Name  : Language.OCR~~~en-US~0.0.1.0
State : Installed

Name  : Language.OCR~~~it-IT~0.0.1.0
State : Installed
```

**Ubuntu console font parameters:**
FONTFACE="Fixed"
FONTSIZE="8x16"

**Comment by TheJoeFin** [comment]
This is a bug with the underlying OCR models being used. I am eager to use updated models when they become available to 3rd party developers, but currently the best way to improve would be to use the Text Grab settings to install Tesseract and use those models.

**Comment by Zio3D** [comment]
OK, thanks, I'll follow your advice 😃
