### ISSUE TITLE
Fullscreen Grab does not work

### ISSUE THREAD

**Issue by vivadavid** [TheJoeFin/Text-Grab#487]
Hi, Joe,

I've noticed some problems with version 4.5.1, mainly that _Fullscreen Grab_ doesn't work. You run it, but you can't select a particular language and, when you select an area to be recognized, nothing happens.

Also, when you click on the _Settings_ section from the Windows taskbar, you get an empty window.

For testing purposes, I decided to delete the _Text Grab_ folder located in the _AppData_ folder, hoping that, by resetting everything, the problem might be solved. After doing that, I can't run Text Grab any more. I double click on the EXE file and nothing happens.

I've downloaded version 4.5.0 and things work as usual.

Let me know if you need further information. Thanks!

**Where is the bug**

- Fullscreen Grab
- Settings Window

**Screenshots**

https://github.com/user-attachments/assets/75e965e1-dcf8-4797-83ad-e1946c197f15

**Where did you get Text Grab?**
- GitHub releases
     - Exe

**Desktop (please complete the following information):**
 - OS: Windows 11.
 - Version 24H2 (I'm currently an insider).
 - Text Grab Version 4.5.1.

**Comment by TheJoeFin** [comment]
@vivadavid can you try redownload the the files from 4.5.1 and retest. Users were reporting this issue (it is a bug with Visual Studio preview and .NET 9) but I have worked around the issue for the latest build.

**Comment by vivadavid** [comment]
Hi, Joe,

It works now: thanks!

I didn't know Text Grab had been recompiled. Unfortunately, you only get a notification when there's a new release.

I take the opportunity to let you know that, in _Settings_, you find the following option twice: "Run Text Grab in the background and enable hotkeys". It's under _General Settings_ and under _ShortCut Key Settings_.

**Comment by TheJoeFin** [comment]
@vivadavid The duplicate setting is intentional because it does the same thing but could be logically placed in either spot
