### ISSUE TITLE
Can I use usb camera to ocr electric balance's digital number every second and send to a text file? 

### ISSUE THREAD

**Issue by ss1000301** [TheJoeFin/Text-Grab#489]
Can I use usb camera to ocr electric balance's digital number every second and send to a text file?
How to use
I found it can read a data one time
but i want to read the data 10 minutes
who can teach me
thank you

**Comment by TheJoeFin** [comment]
Text Grab does not have camera functionality (see #251) or capturing on a timer (see #283)
