### ISSUE TITLE
How to use this repo as Text Extractor in PowerToy

### ISSUE THREAD

**Issue by zydjohnHotmail** [TheJoeFin/Text-Grab#497]
Hi,
I can use Text Extractor in PowerToy for my Windows 11 PC.
However, in order to use it, I have to install OCR for Windows but I think it is necessary, but I have to install PowerToy, which has a lot of features, which are not necessary for my project.
I want to know if I want to write one WinForms project and try to grab text from an area of my PC screen, like: start point (100, 100) with size of (200, 50) pixels, then run C# code to recognize the text in that area using the OCR installed for PowerToy.
Please show me a sample code for this job, so I don't have to install PowerToy to do this.
I am using Visual Studio 2022 version 17.12.1 on Windows 11 (Version 23H2 OS build 22631.4541)
Thanks,

**Comment by zydjohnHotmail** [comment]
Hi, 
Thank you very much for your quick reply.  I will take a look, but I have one concern, due to other requirements, currently I can only use WinForms project to run the Text Extractor in PowerToy, but the url you provided seem I have to use UWP, which is not WinForms project, I don't know if I can use this for my WinForms project.
Please advise on this issue.
Thanks,

**Comment by TheJoeFin** [comment]
https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-enhance
