### ISSUE TITLE
Add possibility to grab tooltips

### ISSUE THREAD

**Issue by bbuerger** [TheJoeFin/Text-Grab#64]
I'm not able to get text from a tooltip, because it disappears when using text-grab.
I understand the technical limitation that text-grab is started as a new process => maybe it is not possible to do this or difficult because the image must be captured before opening a new window.
Tools like greenshot take an image preserving the screenshot (but they are already loaded in memory)
The issue is not important because there is a good workaround (maybe you can add this as a hint for other users):
First use greenshot via hotkey and then text-grab via hotkey.

**Comment by TheJoeFin** [comment]
Related to #66, but for that to work on ToolTips I think the Fullscreen Grab will have to take a full screen capture and apply it to the Window to "Freeze" the pane
