### ISSUE TITLE
Region selection rectangle can disconnect from mouse cursor when moving mouse quickly

### ISSUE THREAD

**Issue by TheJoeFin** [TheJoeFin/Text-Grab#79]

**Comment by TheJoeFin** [comment]
need to add .CaptureMouse() on mouse down

**Comment by TheJoeFin** [comment]
.CaptureMouse() helps but does not solve the problem

**Comment by AntonyCorbett** [comment]
My PR only fixes the FullScreen mode. If you're happy with the fix we can apply to GrabFrame too.

**Comment by AntonyCorbett** [comment]
@TheJoeFin Sorry, I didn't notice that this was assigned to you until I'd finished :(

**Comment by TheJoeFin** [comment]
@AntonyCorbett no problem, I thought CaptureMouse() would have solved this so I had assigned myself, but I should have unassigned myself when I saw this issue remained
