### ISSUE TITLE
Text works great... code seems to scramble (like tables).

### ISSUE THREAD

**Issue by jmees** [TheJoeFin/Text-Grab#86]
Simple test of screen grabbing some SQL and then trying to re-create it with Text Grab fails.
Original text converted to image:

> Select x.* from DimSomeExpandedView x 
> inner join DimWildView m on x.wildId = m.wildId
> where x.T8 like 'TEST%'
> and x.T1 = 'TRRR'
> and m.T2 not in ('Non-3CP','Old-3CP')
> and x.G2 = B1
> and x.T44 > 0
> and x.T45 > 0
> and x.Available > 0
> and m.T99 = 'OPT'
> and m.T33 = 0

Resulting text from image:
> Select x. *
> inner
> where
> join
> x.T8
> from DimSomeExpandedView x
> DimWi1dView m on x.wildld
> like 'TEST%'
> 'TRRR'
> m. wildld
> and
> and
> and
> and
> and
> and
> and
> and
> m.T2 not in ('Non-3CP', 'Old-3CP')
> x.G2
> T44 >
> x.
> x.T45 > e
> x. Available > e
> ' OPT '
> m. T99
> m.T33

`
Removed colorized font, tested with some specific symbol changes... no difference.
(Still a great tool, just surprised at this result with this code).

**Comment by TheJoeFin** [comment]
Hello @jmees, this is an issue I'm aware of. Right now Text Grab relies upon the Windows 10 OCR engine to do the OCR and give each recognized word a line number. Frequently the OCR works well, but the lines can be way off. 

There are plans to improve this in two ways. 
1. Table Mode #11 
2. Improve recognized word line 

If you provide a screenshot of the text you were trying to recognize that would be helpful when testing these features to make sure they are working well.

**Comment by jmees** [comment]
Thanks for the speedy feedback. 
Did not want to clutter feedback with screenshots.
To repro:  [Win]+[Shift]+[S] the "Original text converted to image" text from issue listing into some paint program (or use snipping tool) and then try reverse the process with Text Grab into any editor. FYI, tried it on two different resolution screens (1920X1080 and 3440X1440) with same results. Also, Android Office Tool - Image to Text works correctly for this example, but I suspect that it's cloud based.
