### ISSUE TITLE
Some characters are recognised incorrectly or not at all

### ISSUE THREAD

**Issue by beerisgood** [TheJoeFin/Text-Grab#9]
Example picture:
![image](https://user-images.githubusercontent.com/9625159/103351816-b2376980-4aa4-11eb-9e16-1b8a7f18275d.png)

Extracted text:
> Das Kennwort muss 8-64 Zeichen lang seim
Folgende Zeichen sind zulässig: a-z, A-ZI 0-9,
-+='l 0 0; und Platz.

as you can see, an "n." becomes an "m" and a "Z," becomes a "ZI".
special letters are missing completely

**Comment by TheJoeFin** [comment]
Text Grab uses the OCR which is built into Windows 10 which is not perfect. Clearly one of the places where it does not perform well is with a string of just symbols. I'm working to improve the contrast when a screenshot is taken, but there are limitations to what OCR is capable of doing.

I believe improving Microsoft's OCR engine for Windows is out of scope for this tool.
